### ISSUE TITLE
Problem with Office2016SKULess.munki

### ISSUE THREAD

**Issue by asatnikscales** [arubdesu/office-recipes#4]
When I try to run the com.github.autopkg.arubdesu-recipes.munki.Office2016Suite recipe in autopkg I get the following error:
Can't download http://macadmins.software/versions.xml: <urlopen error EOF occured in violation of protocol (_ssl.c:590)>

Any ideas how to work around this?

**Comment by arubdesu** [comment]
Thanks for reporting! I don’t personally run this exact recipe but I’ll look into addressing the root cause.

**Comment by asatnikscales** [comment]
Thanks!

**Comment by Darkomen78** [comment]
Error still there

**Comment by asatnikscales** [comment]
The problem was resolved for me when I upgraded my machine to MacOS 10.13.
