### ISSUE TITLE
No module named ‘urllib2’ 

### ISSUE THREAD

**Issue by mikaellofgren** [arubdesu/office-recipes#7]
Hi
Updated to Autopkg 2.0.2 get this error:
/Library/AutoPkg/RecipeRepos/com.github.arubdesu.office-recipes/Office2019Suite-SKUless/OfficeSuiteSKULessVersionProvider.py: No module named 'urllib2' Failed.

urlib2 seems gone in python3.

**Comment by homebysix** [comment]
FWIW, @rtrouton's copy of that processor has been updated with URLGetter, which is compatible with both Py2 and Py3.

https://github.com/autopkg/rtrouton-recipes/blob/master/MicrosoftOffice365Suite/OfficeSuiteSKULessVersionProvider.py

Might make sense to PR those changes back to this repo.

**Comment by apizz** [comment]
Yes, just ran into this myself.  The OfficeSuiteSKUlessVersionProvider in arub's autopkg repo has Python3 & Python2 import checks, just not this one.

**Comment by arubdesu** [comment]
Anyone want to throw a PR my way I’m more than happy to give it a sniff and a merge 🙏

**Comment by apizz** [comment]
Started down that path yesterday, but got side tracked.  Will try and get one going soon ...

**Comment by mikaellofgren** [comment]
I took rtrouton OfficeSuiteSKULessVersionProvider.py and replaced the [non-working] OfficeSuiteSKULessVersionProvider.py locally and its seems to been working since I reported this..

**Comment by apizz** [comment]
The problem for me is that rtrouton's hard-codes the desired version of Office.  Want people to be able to decide whether to choose `o365`, `vl2019` or `vl2016`

**Comment by arubdesu** [comment]
Update is pushed (assuming it fixes that which was previously broken, but I haven't actually tested). Feel free to reopen/yell at me if it's still not right, otherwise all thanks to @apizz!

**Comment by apizz** [comment]
Can confirm that after pulling updated repo & updating recipe trust that all is happy again!  Thanks for getting this pulled quickly, @arubdesu!
